### ISSUE TITLE
关于DKMS的疑问及勘误

### ISSUE THREAD

**Issue by kalashnlkov** [rocksaying/rocksaying.github.io#1]
hi 这个post是针对
[Linux DKMS 機制導入筆記](https://github.com/rocksaying/rocksaying.github.io/blob/da7048f454fa1c7a3fba07436a44048b4e1d4e50/_posts/2015-12-17-Linux_DKMS_%E6%A9%9F%E5%88%B6%E5%B0%8E%E5%85%A5%E7%AD%86%E8%A8%98.md)的。 虽然这是7年前的分享但是还是想交流一下。我使用的dkms版本是 ubuntu18.04上的dkms 2.2.1.0
其中提到

> DEST_MODULE_LOCATION[#]
模組檔案要放置的目的目錄。這是必要指令，但目的目錄可一律寫 “/updates/dkms” 。
>我懷疑這個指令有 bug 。不論我填 “/kernel”, “/extra” 或其他目錄，它實際上都複製到 “/updates/dkms” ，無視設定。

是因为给定的目录被override了，可见
```bash
# Override location for specific kernels                                                       
dest_module_location[$index]="$(override_dest_module_location ${dest_module_location[$index]})"
```
debian系的会放到`/updates/dkms`， rh系的放到`/extra`

而这里的`MAKE[#]`不晓得是否有测试过当#>0时是否生效？
我的理解是当`MAKE_MATCH[#]`为真时，`MAKE[#]`会替换之前的make指令。换言之一个module只有一个MAKE生效。
因此这里的若干个`MAKE[1]="echo nothing"` 都不会执行。不知是否有误，期待你的回复。

**Comment by rocksaying** [comment]
接下來的回復，以 https://linux.die.net/man/8/dkms 的內容為準。

1. DEST_MODULE_LOCATION 算是文件敘述bug吧

文件先說必要(required)，但後面又補充特定的 distribution 會忽略它(ignored)。

> DEST_MODULE_LOCATION is ignored on Fedora Core 6 and higher, Red Hat Enterprise Linux 5 and higher, Novell SuSE Linux Enterprise Server 10 and higher, Novell SuSE Linux 10.0 and higher, and Ubuntu. Instead, the proper distribution-specific directory is used. 

我已經忘了當年我看的文件有沒有寫這段。總之上面列的這些 distribution 就是照你說的 override 了，無視我們在 DEST_MODULE_LOCATION 給的位置。

2. MAKE_MATCH 的部份你說的沒錯。

只是我的案例列了 3 個 module ，卻在 MAKE[0] 時就把 3 個 module 都搞定了。
這個狀況算是特例。總之我想找個簡單的方法讓 DKMS 不再 make 另外 2 個 module。

> If no MAKE directive is specified or if no MAKE_MATCH matches the kernel being built for, DKMS will attempt to use a generic MAKE command to build your module. 

印象中，在這個案例中加了 `MAKE[1]="echo nothing"`, `MAKE[2]="echo nothing"` 之後，DKMS 就沒有向我 complain 任何事了。我應該不會沒事去加這2行。

**Comment by shirock** [comment]
closed
