### ISSUE TITLE
MS SQL Server 前置詞 instered 錯誤

### ISSUE THREAD

**Issue by Larrydon** [rocksaying/rocksaying.github.io#2]
https://www.rocksaying.tw/archives/2022/sql-update-returning.html
在
MS SQL Server 介紹的地方，關於前置詞 instered
寫錯了，範例裡的是對的，正確應該是 [INSERTED]

謝謝您的文章介紹，讓我搜尋到這篇教學

**Comment by shirock** [comment]
謝謝提醒，修正 a0d748652494b1c2f23ff784e3ab9ceb1d9ed88c
